version: "3.9"  # optional since v1.27.0
services:
  quarkus:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - "C:/Users/Dario/.m2:/root/.m2"
      - "./src:/workspace/src"